ALTER TABLE CategoriasMultimedias DROP CONSTRAINT FK_categoriasM2;
ALTER TABLE CategoriasMultimedias ADD CONSTRAINT FK_categoriasM2 FOREIGN KEY (idMultimedia) REFERENCES Multimedias(id) ON DELETE CASCADE;

ALTER TABLE CategoriasMultimedias DROP CONSTRAINT vFK_categoriasM1;
ALTER TABLE CategoriasMultimedias ADD CONSTRAINT FK_categoriasM1 FOREIGN KEY (idCategoria) REFERENCES Categorias(id) ON DELETE CASCADE;

ALTER TABLE PremiosMultimedia DROP CONSTRAINT FK_premiosM2;
ALTER TABLE PremiosMultimedia ADD CONSTRAINT FK_premiosM2 FOREIGN KEY (idMultimedia) REFERENCES Multimedias(id) ON DELETE CASCADE;

ALTER TABLE Series DROP CONSTRAINT FK_series;
ALTER TABLE Series ADD CONSTRAINT FK_series FOREIGN KEY (id) REFERENCES Multimedias(id) ON DELETE CASCADE;

ALTER TABLE Temporadas DROP CONSTRAINT FK_temporada;
ALTER TABLE Temporadas ADD CONSTRAINT FK_temporada FOREIGN KEY (idSerie) REFERENCES Series(id) ON DELETE CASCADE;

ALTER TABLE InfoTemporadas DROP CONSTRAINT FK_infTemp;
ALTER TABLE InfoTemporadas ADD CONSTRAINT FK_infTemp FOREIGN KEY (idTemporada) REFERENCES Temporadas(id) ON DELETE CASCADE;

ALTER TABLE CapitulosSeries DROP CONSTRAINT FK_capSeries;
ALTER TABLE CapitulosSeries ADD CONSTRAINT FK_capSeries FOREIGN KEY (idTemporada) REFERENCES Temporadas(id) ON DELETE CASCADE;

ALTER TABLE InfoCapitulosSeries DROP CONSTRAINT FK_inf_capSeries;
ALTER TABLE InfoCapitulosSeries ADD CONSTRAINT FK_inf_capSeries FOREIGN KEY (idCapitulo) REFERENCES CapitulosSeries(id) ON DELETE CASCADE;

ALTER TABLE Documentales DROP CONSTRAINT FK_documentales;
ALTER TABLE Documentales ADD CONSTRAINT FK_documentales FOREIGN KEY (id) REFERENCES Multimedias(id) ON DELETE CASCADE;

ALTER TABLE CapitulosDocumentales DROP CONSTRAINT FK_capDoc;
ALTER TABLE CapitulosDocumentales ADD CONSTRAINT FK_capDoc FOREIGN KEY (idDocumental) REFERENCES Documentales(id) ON DELETE CASCADE;

ALTER TABLE InfoCapitulosDocumentales DROP CONSTRAINT FK_inf_capDoc;
ALTER TABLE InfoCapitulosDocumentales ADD CONSTRAINT FK_inf_capDoc FOREIGN KEY (idCapitulo) REFERENCES CapitulosDocumentales(id) ON DELETE CASCADE;

ALTER TABLE Actua DROP CONSTRAINT FK_actua1;
ALTER TABLE Actua ADD CONSTRAINT FK_actua1 FOREIGN KEY (idMultimedia) REFERENCES Multimedias(id) ON DELETE CASCADE;

ALTER TABLE Actua DROP CONSTRAINT FK_actua2;
ALTER TABLE Actua ADD CONSTRAINT FK_actua2 FOREIGN KEY (idActor) REFERENCES Actores(id) ON DELETE CASCADE;

ALTER TABLE PremiosActores DROP CONSTRAINT FK_premA2;
ALTER TABLE PremiosActores ADD CONSTRAINT FK_premA2 FOREIGN KEY (idActor) REFERENCES Actores(id) ON DELETE CASCADE;

ALTER TABLE Observa DROP CONSTRAINT FK_observa1;
ALTER TABLE Observa ADD CONSTRAINT FK_observa1 FOREIGN KEY (idMultimedia) REFERENCES Multimedias(id) ON DELETE CASCADE;

ALTER TABLE Observa DROP CONSTRAINT FK_observa2;
ALTER TABLE Observa ADD CONSTRAINT FK_observa2 FOREIGN KEY (idPlantilla) REFERENCES Plantillas(id) ON DELETE CASCADE;

ALTER TABLE Solicita DROP CONSTRAINT FK_solicita1;
ALTER TABLE Solicita ADD CONSTRAINT FK_solicita1 FOREIGN KEY (idSolicitud) REFERENCES Solicitudes(id) ON DELETE CASCADE;

ALTER TABLE Peliculas DROP CONSTRAINT FK_peliculas;
ALTER TABLE Peliculas ADD CONSTRAINT FK_peliculas FOREIGN KEY (id) REFERENCES Multimedias(id) ON DELETE CASCADE;
