/*COMO USUARIO QUIERO CONSULTAR TODAS LAS PELICULAS*/



SELECT PA_USUARIO.Consultar_multimedia(null) FROM DUAL;



/*LUEGO ESCOJO VER LA PRIMERA PELICULA QUE ENCUENTRO*/

CALL PA_ADMINISTRADOR.Adicionar_observa(0,6,null,1);


/*LUEGO QUIERO VER MI HISTORIAL DE VISTAS YA QUE TENGO GANAS DE VOLVER A VER UNA PELICULA LA CUAL NO RECUERDO EL NOMBRE*/

SELECT PA_USUARIO.CONSULTAR_OBSERVA(NULL,6) FROM DUAL;



/*LUEGO QUIERO CONSULTAR LAS SERIES MAS VISTAS */

SELECT PA_USUARIO.CONSULTAR_SERIES(null) FROM DUAL;


/*HE DECIDIDO VER LA PRIMERA QUE HE ENCONTRADO*/

CALL PA_ADMINISTRADOR.Adicionar_observa(1587,6,null,1);


/*ANTES DE TERMINAR QUIERO VER UN DOCUMENTAL, YA QUE HE ESCUCHADO QUE SE APRENDE MUCHO VIENDOLOS*/

/*PARA ESTO HE DECIDIDO VER SOBRE DRAMA*/

/*ASÍ QUE PRIMERO LOS CONSULTARE PARA ESCOGER UNO*/

SELECT PA_USUARIO.CONSULTAR_DOCUMENTAL(null)FROM DUAL;


/*HE DECIDIDO OBSERVAR EL DOCUMENTAL CON EL NOMBRE FLACOS COLEGAS*/

CALL PA_ADMINISTRADOR.Adicionar_observa(2020,6,null,1);


/*FIN*/